import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ["Montserrat", "sans-serif"],
        body: ["Montserrat", "Lato", "sans-serif"],
        editorial: ["Cormorant Garamond", "serif"],
        hand: ["Caveat", "cursive"],
        mono: ["Montserrat", "Lato", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["3.5rem", { lineHeight: "1.1", fontWeight: "800", letterSpacing: "-0.02em" }],
        "display-lg": ["2.75rem", { lineHeight: "1.15", fontWeight: "800", letterSpacing: "-0.015em" }],
        "heading-lg": ["2rem", { lineHeight: "1.2", fontWeight: "700" }],
        "heading-md": ["1.5rem", { lineHeight: "1.3", fontWeight: "700" }],
        "heading-sm": ["1.125rem", { lineHeight: "1.4", fontWeight: "600" }],
        "card-title": ["var(--card-title-size)", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["var(--body-size)", { lineHeight: "var(--body-line-height)", fontWeight: "500" }],
        "body-md": ["0.875rem", { lineHeight: "1.6", fontWeight: "500" }],
        "body-sm": ["0.75rem", { lineHeight: "1.5", fontWeight: "500" }],
        "section-label": ["var(--label-size)", { lineHeight: "1.2", fontWeight: "600", letterSpacing: "var(--label-tracking)" }],
        "quote": ["var(--quote-size)", { lineHeight: "1.6", fontWeight: "400" }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          soft: "hsl(var(--primary-soft))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Phase colours
        "phase-menstrual": "hsl(var(--phase-menstrual))",
        "phase-follicular": "hsl(var(--phase-follicular))",
        "phase-ovulatory": "hsl(var(--phase-ovulatory))",
        "phase-luteal": "hsl(var(--phase-luteal))",
        // Wildflower accents
        coral: "hsl(var(--coral-flame))",
        bloom: "hsl(var(--bloom-blush))",
        "petal-gold": "hsl(var(--petal-gold))",
        "sage-mist": "hsl(var(--sage-mist))",
        "lavender-dust": "hsl(var(--lavender-dust))",
        sketch: "hsl(var(--sketch))",
        // Legacy compat
        sage: "hsl(var(--phase-follicular))",
        ivory: "hsl(var(--background))",
        forest: "hsl(var(--foreground))",
        burgundy: "hsl(var(--phase-menstrual))",
        gold: "hsl(var(--phase-ovulatory))",
        plum: "hsl(var(--phase-luteal))",
        cyan: "hsl(var(--coral-flame))",
        network: "hsl(var(--sketch))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      spacing: {
        "space-xs": "var(--space-xs)",
        "space-sm": "var(--space-sm)",
        "space-md": "var(--space-md)",
        "space-lg": "var(--space-lg)",
        "space-xl": "var(--space-xl)",
        "space-2xl": "var(--space-2xl)",
        "space-3xl": "var(--space-3xl)",
        "card-pad": "var(--card-padding)",
        "card-gap": "var(--card-gap)",
        "section-gap": "var(--section-gap)",
        "safe-top": "env(safe-area-inset-top, 0px)",
        "safe-bottom": "env(safe-area-inset-bottom, 0px)",
        "safe-left": "env(safe-area-inset-left, 0px)",
        "safe-right": "env(safe-area-inset-right, 0px)",
        "header": "var(--header-height)",
        "nav": "var(--nav-height)",
      },
      padding: {
        safe: "env(safe-area-inset-top)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "var(--radius-sm)",
        xl: "var(--radius-lg)",
        "2xl": "var(--radius-xl)",
        card: "var(--radius-card)",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        medium: "var(--shadow-medium)",
        elevated: "var(--shadow-elevated)",
        glow: "var(--shadow-glow)",
      },
      transitionTimingFunction: {
        calm: "var(--ease-calm)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
        gentle: "var(--duration-gentle)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0", opacity: "0" },
          to: { height: "var(--radix-accordion-content-height)", opacity: "1" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)", opacity: "1" },
          to: { height: "0", opacity: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "node-pulse": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.8" },
        },
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        "confetti-burst": {
          "0%": { transform: "scale(0) rotate(0deg)", opacity: "1" },
          "50%": { opacity: "1" },
          "100%": { transform: "scale(1.5) rotate(180deg)", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "node-pulse": "node-pulse 3s ease-in-out infinite",
        shimmer: "shimmer 2s ease-in-out infinite",
        "confetti-burst": "confetti-burst 0.8s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
