-- 1. New goal category: Martial Arts
INSERT INTO public.goal_categories (id, slug, label, description, intensity_min, intensity_max, hormonal_notes, sort_order)
VALUES
  ('gc-018', 'martial_arts', 'Martial Arts & Combat Conditioning',
   'Build power, agility and discipline through bodyweight combat drills, kicks, strikes and shadow work.',
   3, 5,
   'High-intensity striking can be demanding in luteal phase — scale rounds and add extra rest. Best matched to follicular and ovulatory windows.',
   18)
ON CONFLICT (id) DO NOTHING;

-- 2. Training programs (16)
INSERT INTO public.training_programs
  (id, goal_category_id, title, description, who_its_for, duration_weeks, sessions_per_week,
   intensity_level, equipment_needed, slug, phase_structure, evidence_basis, tags)
VALUES
  ('tp-forever-strong','gc-011','Forever Strong Power Plan','A 6-week dumbbell-based strength programme rebuilding power and bone density for women 40+. Compound lifts, supersets and progressive overload.','Women in perimenopause or menopause who want to feel strong, lift confidently and protect bone density.',6,3,4,ARRAY['dumbbells','bench','mat'],'forever-strong-power-plan','2 phases × 3 weeks','Adapted from Dr Gabrielle Lyon — Forever Strong (2023)',ARRAY['strength','menopause','bone-density']),
  ('tp-4w-beginners','gc-004','4 Weeks for Beginners','A gentle ramp into resistance training. Master the foundational movement patterns: squat, hinge, push, pull, carry.','Total beginners or anyone returning from a long break.',4,3,2,ARRAY['dumbbells','mat'],'4-weeks-for-beginners','Single phase — repeated','Foundational strength principles (Starting Strength, Rippetoe)',ARRAY['beginner','foundations']),
  ('tp-anatomy-exercise','gc-009','Anatomy of Exercise — Foundations','Learn the major muscle groups by training them with intent. Each session targets a specific anatomical region.','Intermediate lifters who want to understand muscle activation deeply.',8,4,3,ARRAY['dumbbells','barbell','bench'],'anatomy-of-exercise','2 phases × 4 weeks','DK Anatomy of Exercise (Pat Manocchia)',ARRAY['hypertrophy','education']),
  ('tp-complete-training-guide','gc-009','Complete Training Guide','A full periodised plan covering hypertrophy, strength and conditioning over 12 weeks.','Intermediate–advanced trainees ready for structured periodisation.',12,4,4,ARRAY['barbell','dumbbells','rack','bench'],'complete-training-guide','3 phases × 4 weeks','NSCA Essentials of Personal Training',ARRAY['strength','hypertrophy','periodisation']),
  ('tp-butt-legs','gc-008','Butt & Legs Sculpt','Targeted lower-body programme using hip thrusts, RDLs, lunges and glute activation work.','Anyone wanting visible glute and leg development.',8,3,3,ARRAY['dumbbells','barbell','bands','bench'],'butt-legs-sculpt','2 phases × 4 weeks','Glute Lab — Bret Contreras',ARRAY['glutes','lower-body']),
  ('tp-hypertrophy','gc-009','Muscle Hypertrophy Builder','Volume-focused programme to maximise muscle growth across all major movement patterns.','Lifters with 3+ months of training experience.',10,4,4,ARRAY['dumbbells','barbell','bench','cables'],'muscle-hypertrophy-builder','2 phases × 5 weeks','Schoenfeld — Science of Hypertrophy',ARRAY['hypertrophy','volume']),
  ('tp-next-level-meno','gc-011','Next Level Menopause Strength','Heavy compound lifts adapted for menopause. Builds strength while supporting hormonal shifts.','Women in peri/menopause who already lift weights and want to progress.',12,3,4,ARRAY['barbell','dumbbells','rack','bench'],'next-level-menopause','3 phases × 4 weeks','Next Level — Stacy Sims',ARRAY['menopause','strength','hormones']),
  ('tp-ashtanga','gc-012','Ashtanga Yoga Primary','A flowing primary series practice — sun salutations, standing and seated postures, finishing sequence.','Practitioners with 6+ months of yoga who want a structured daily practice.',8,5,3,ARRAY['mat'],'ashtanga-primary','Single continuous phase','Pattabhi Jois — Yoga Mala',ARRAY['yoga','flow','traditional']),
  ('tp-relax-stretch','gc-015','Relax Into Stretch','Slow, parasympathetic stretching using the contract-relax method to safely deepen range of motion.','Anyone with chronic tightness wanting safe, lasting flexibility.',6,4,1,ARRAY['mat','strap'],'relax-into-stretch','Single phase','Pavel Tsatsouline — Relax Into Stretch',ARRAY['flexibility','recovery']),
  ('tp-stretching-essentials','gc-015','Stretching Essentials','Daily 15-minute mobility flows covering hips, shoulders, spine and hamstrings.','Desk workers and anyone wanting daily mobility maintenance.',4,5,1,ARRAY['mat'],'stretching-essentials','Single phase','Anatomy of Stretching (Brad Walker)',ARRAY['mobility','daily']),
  ('tp-somatic-foundations','gc-001','Somatic Exercise Foundations','Gentle nervous-system regulating movements — pandiculation, micro-movements and breath work.','Anyone with chronic stress, tension or trauma history seeking nervous-system care.',6,4,1,ARRAY['mat'],'somatic-foundations','Single phase','Thomas Hanna — Somatics',ARRAY['somatic','nervous-system','gentle']),
  ('tp-shaolin','gc-018','Shaolin Workout','28-day fitness programme drawing from traditional Shaolin training: stances, kicks, strikes, conditioning.','Active trainees wanting power, agility and a martial-arts foundation.',4,4,4,ARRAY['mat'],'shaolin-workout','Single phase × 4 weeks','Sifu Shi Yan Ming — Shaolin Workout',ARRAY['martial-arts','conditioning','agility']),
  ('tp-female-body-bible','gc-007','Female Body Bible','A holistic strength + conditioning programme phased around the menstrual cycle.','Cycling women wanting to train in sync with their hormones.',12,4,3,ARRAY['dumbbells','barbell','bench'],'female-body-bible','4 phases — one per cycle phase','The Female Body Bible — Dr Emma Ross',ARRAY['cycle-synced','tone']),
  ('tp-maffetone','gc-017','Maffetone Method','Build a deep aerobic base by training at heart rate ≤ (180 − age). Slow, steady, sustainable.','Endurance athletes or anyone wanting fat-burning aerobic fitness.',12,5,2,ARRAY['hr-monitor'],'maffetone-method','Single phase','Dr Phil Maffetone — Big Book of Endurance',ARRAY['aerobic','endurance','low-hr']),
  ('tp-thr-training','gc-005','Total Heart Rate Training','Five training zones used strategically across the week for fat loss and cardiovascular health.','Anyone with a heart-rate monitor wanting smart cardio.',8,4,3,ARRAY['hr-monitor'],'total-heart-rate-training','2 phases × 4 weeks','Total Heart Rate Training — Joel Friel',ARRAY['cardio','zones','fat-loss']),
  ('tp-bbg-1','gc-006','BBG 1.0 — Bikini Body Guide','12-week high-intensity circuit programme combining plyometrics and resistance for full-body conditioning.','Active trainees who enjoy intense circuit-style sessions.',12,3,4,ARRAY['dumbbells','bench','mat','step'],'bbg-1-0','3 phases × 4 weeks','Kayla Itsines — Bikini Body Guide',ARRAY['hiit','circuit','conditioning'])
ON CONFLICT (id) DO NOTHING;

-- 3. Phases
INSERT INTO public.program_phases (id, program_id, phase_number, title, week_start, week_end, rpe_target_min, rpe_target_max, phase_goal)
VALUES
  ('pp-fs-1','tp-forever-strong',1,'Foundation',1,3,6.0,7.5,'Groove the major lifts and build dumbbell capacity.'),
  ('pp-4wb-1','tp-4w-beginners',1,'Movement Patterns',1,4,5.0,6.5,'Master squat, hinge, push, pull and carry with light loads.'),
  ('pp-anat-1','tp-anatomy-exercise',1,'Upper / Lower Foundations',1,4,6.0,7.5,'Learn how each major muscle activates under tension.'),
  ('pp-ctg-1','tp-complete-training-guide',1,'Hypertrophy Block',1,4,6.5,8.0,'Accumulate volume across all movement patterns.'),
  ('pp-bl-1','tp-butt-legs',1,'Glute Activation & Volume',1,4,6.0,7.5,'Wake up the glutes and build lower-body capacity.'),
  ('pp-hyp-1','tp-hypertrophy',1,'Volume Accumulation',1,5,7.0,8.5,'High-volume work driving hypertrophy adaptations.'),
  ('pp-nlm-1','tp-next-level-meno',1,'Strength Foundation',1,4,7.0,8.5,'Heavy compound lifts adapted for menopause.'),
  ('pp-ash-1','tp-ashtanga',1,'Primary Series',1,8,5.0,7.0,'Daily practice of the full primary series.'),
  ('pp-rs-1','tp-relax-stretch',1,'Tension Release',1,6,3.0,5.0,'Use contract-relax to deepen safely.'),
  ('pp-se-1','tp-stretching-essentials',1,'Daily Mobility',1,4,3.0,5.0,'Cover full-body ROM each day.'),
  ('pp-som-1','tp-somatic-foundations',1,'Pandicular Reset',1,6,2.0,4.0,'Re-pattern the nervous system gently.'),
  ('pp-sha-1','tp-shaolin',1,'Stances & Strikes',1,4,6.0,8.0,'Build the foundational stances, kicks and strikes.'),
  ('pp-fbb-1','tp-female-body-bible',1,'Follicular Build',1,3,7.0,8.5,'Capitalise on rising oestrogen with heavy training.'),
  ('pp-maf-1','tp-maffetone',1,'Aerobic Base',1,12,3.0,5.0,'All training at MAF (180 − age) heart rate.'),
  ('pp-thr-1','tp-thr-training',1,'Zone 2 Foundation',1,4,4.0,6.0,'Build a strong zone 2 aerobic base.'),
  ('pp-bbg-1','tp-bbg-1',1,'Resistance Circuits',1,4,7.0,8.5,'7-minute circuits repeated for full-body conditioning.')
ON CONFLICT (id) DO NOTHING;

-- 4. Workouts (32)
INSERT INTO public.workout_templates
  (id, phase_id, program_id, session_number, title, day_label, session_type, warmup_notes, cooldown_notes, session_notes, estimated_duration_mins)
VALUES
  ('wt-fs-1','pp-fs-1','tp-forever-strong',1,'Lower Body Power','Day 1','strength','5 min easy walk + bodyweight squats','5 min slow walk + hamstring stretch','Focus on quality reps. Rest 90s between sets.',45),
  ('wt-fs-2','pp-fs-1','tp-forever-strong',2,'Upper Body Push & Pull','Day 2','strength','Arm circles + scap retractions','Doorway pec stretch + shoulder rolls','Superset the press and row to save time.',40),
  ('wt-4wb-1','pp-4wb-1','tp-4w-beginners',1,'Full Body A','Day 1','strength','5 min march in place','Light stretch','Light dumbbells. Form first.',30),
  ('wt-4wb-2','pp-4wb-1','tp-4w-beginners',2,'Full Body B','Day 2','strength','Cat-cows + arm swings','Childs pose 1 min','Same patterns, different angle.',30),
  ('wt-anat-1','pp-anat-1','tp-anatomy-exercise',1,'Upper Body Anatomy','Day 1','strength','Band pull-aparts','Pec stretch','Slow eccentric to feel each muscle.',50),
  ('wt-anat-2','pp-anat-1','tp-anatomy-exercise',2,'Lower Body Anatomy','Day 2','strength','Glute bridges 2x15','Quad + hip flexor stretch','Pause at the bottom of squats.',50),
  ('wt-ctg-1','pp-ctg-1','tp-complete-training-guide',1,'Push Day','Day 1','strength','Shoulder mobility 5 min','Triceps stretch','Top set then 2 back-off sets.',60),
  ('wt-ctg-2','pp-ctg-1','tp-complete-training-guide',2,'Pull Day','Day 2','strength','Band rows + scap pulls','Lat hang','Drive elbows down on rows.',60),
  ('wt-bl-1','pp-bl-1','tp-butt-legs',1,'Glute-Focused','Day 1','strength','Banded glute bridges 2x15 + monster walks','Pigeon stretch','Squeeze glutes hard at lockout.',45),
  ('wt-bl-2','pp-bl-1','tp-butt-legs',2,'Quad & Hamstring','Day 2','strength','Bodyweight squats 2x15','Quad + hamstring stretch','Slow on the way down.',45),
  ('wt-hyp-1','pp-hyp-1','tp-hypertrophy',1,'Chest & Triceps','Day 1','strength','Light press 2x10','Chest doorway stretch','Last set to RIR 1-2.',55),
  ('wt-hyp-2','pp-hyp-1','tp-hypertrophy',2,'Back & Biceps','Day 2','strength','Band pull-aparts 2x15','Lat stretch','Squeeze and hold each row 1s.',55),
  ('wt-nlm-1','pp-nlm-1','tp-next-level-meno',1,'Heavy Lower','Day 1','strength','Dynamic warm-up 8 min','Walking 5 min','Heavy compound work — rest 2-3 min between sets.',55),
  ('wt-nlm-2','pp-nlm-1','tp-next-level-meno',2,'Heavy Upper','Day 2','strength','Band warm-up + light press','Shoulder mobility','Push hard. Strength is the goal.',55),
  ('wt-ash-1','pp-ash-1','tp-ashtanga',1,'Primary Series — Standing','Day 1','yoga','5 sun salutations A','Final 3 min savasana','Move with the breath. Ujjayi throughout.',60),
  ('wt-ash-2','pp-ash-1','tp-ashtanga',2,'Primary Series — Seated','Day 2','yoga','5 sun salutations B','Savasana','Hold each pose 5 breaths.',60),
  ('wt-rs-1','pp-rs-1','tp-relax-stretch',1,'Lower Body Release','Day 1','stretch','3 min light walk','Diaphragmatic breathing 2 min','Contract 6s, relax, deepen.',30),
  ('wt-rs-2','pp-rs-1','tp-relax-stretch',2,'Upper Body Release','Day 2','stretch','Shoulder rolls','Box breathing 2 min','Never force — relax into it.',30),
  ('wt-se-1','pp-se-1','tp-stretching-essentials',1,'Hips & Hamstrings','Day 1','stretch','March in place 2 min','Slow breaths','Hold each 30-45s.',15),
  ('wt-se-2','pp-se-1','tp-stretching-essentials',2,'Shoulders & Spine','Day 2','stretch','Arm swings','Childs pose','Daily mobility hit.',15),
  ('wt-som-1','pp-som-1','tp-somatic-foundations',1,'Arch & Flatten','Day 1','somatic','Lie down, sense body','Rest 3 min','Move slowly. Sense, dont strain.',25),
  ('wt-som-2','pp-som-1','tp-somatic-foundations',2,'Side-Bend Reset','Day 2','somatic','Body scan 2 min','Stillness 3 min','Half-speed. Half-effort.',25),
  ('wt-sha-1','pp-sha-1','tp-shaolin',1,'Stances & Strikes','Day 1','martial-arts','Joint circles + jumping jacks','Light stretch','Hold horse stance 30s × 3. Crisp strikes.',45),
  ('wt-sha-2','pp-sha-1','tp-shaolin',2,'Kicks & Conditioning','Day 2','martial-arts','High knees + hip openers','Quad + hip flexor stretch','Front, side, roundhouse — 10 each side.',45),
  ('wt-fbb-1','pp-fbb-1','tp-female-body-bible',1,'Heavy Lower','Day 1','strength','Glute bridges + squats','Walking','Push intensity in follicular.',55),
  ('wt-fbb-2','pp-fbb-1','tp-female-body-bible',2,'Heavy Upper','Day 2','strength','Band warm-up','Pec stretch','Heavier than usual — energy is high.',55),
  ('wt-maf-1','pp-maf-1','tp-maffetone',1,'MAF Walk/Jog','Day 1','cardio','5 min walking warm-up','5 min cool-down walk','HR must stay under (180 − age). Slow if needed.',45),
  ('wt-maf-2','pp-maf-1','tp-maffetone',2,'MAF Long Effort','Day 2','cardio','5 min walk','5 min walk','Time in zone is the win — not pace.',60),
  ('wt-thr-1','pp-thr-1','tp-thr-training',1,'Zone 2 Steady','Day 1','cardio','5 min easy walk','5 min walk','Conversational pace, ~70% max HR.',45),
  ('wt-thr-2','pp-thr-1','tp-thr-training',2,'Zone 4 Intervals','Day 2','cardio','10 min easy build','10 min easy spin','4 × 4 min hard / 3 min easy.',50),
  ('wt-bbg-1','pp-bbg-1','tp-bbg-1',1,'Legs Circuit','Day 1','hiit','3 min light jog','3 min walk + stretch','7 min AMRAP × 4 rounds, 1 min rest.',30),
  ('wt-bbg-2','pp-bbg-1','tp-bbg-1',2,'Arms & Abs Circuit','Day 2','hiit','Arm circles + jacks','Childs pose','7 min AMRAP × 4 rounds, 1 min rest.',30)
ON CONFLICT (id) DO NOTHING;

-- 5. Workout exercises
INSERT INTO public.workout_exercises
  (id, workout_id, exercise_id, order_index, sets, reps, rest_seconds, rpe_target, load_guidance, is_superset, superset_group)
VALUES
  ('we-fs-1-1','wt-fs-1','Goblet_Squat',0,4,'8-10',90,7.0,'Heavy dumbbell at chest',false,null),
  ('we-fs-1-2','wt-fs-1','ex-003',1,4,'10',90,7.0,'Romanian deadlift form',false,null),
  ('we-fs-1-3','wt-fs-1','Dumbbell_Lunges',2,3,'10/leg',60,6.5,'Moderate dumbbells',false,null),
  ('we-fs-1-4','wt-fs-1','ex-004',3,3,'15',45,6.0,'Banded glute bridge',false,null),
  ('we-fs-2-1','wt-fs-2','Dumbbell_Bench_Press',0,4,'8-10',75,7.0,'Heavy DBs',true,'A'),
  ('we-fs-2-2','wt-fs-2','One-Arm_Dumbbell_Row',1,4,'10/side',75,7.0,'Heavy',true,'A'),
  ('we-fs-2-3','wt-fs-2','Dumbbell_Shoulder_Press',2,3,'10',60,6.5,'Moderate',false,null),
  ('we-fs-2-4','wt-fs-2','Dumbbell_Bicep_Curl',3,3,'12',45,6.0,'Light-moderate',false,null),
  ('we-4wb-1-1','wt-4wb-1','Bodyweight_Squat',0,3,'12',60,5.0,'Bodyweight',false,null),
  ('we-4wb-1-2','wt-4wb-1','ex-014',1,3,'8',60,5.5,'Knees if needed',false,null),
  ('we-4wb-1-3','wt-4wb-1','One-Arm_Dumbbell_Row',2,3,'10/side',60,5.5,'Light',false,null),
  ('we-4wb-1-4','wt-4wb-1','Plank',3,3,'30s',45,5.0,'Hold',false,null),
  ('we-4wb-2-1','wt-4wb-2','Goblet_Squat',0,3,'10',60,5.5,'Light DB',false,null),
  ('we-4wb-2-2','wt-4wb-2','rehab-gl-001',1,3,'12',45,5.0,'Glute bridge',false,null),
  ('we-4wb-2-3','wt-4wb-2','Dumbbell_Shoulder_Press',2,3,'10',60,5.5,'Light',false,null),
  ('we-anat-1-1','wt-anat-1','Dumbbell_Bench_Press',0,4,'10',75,7.0,'Slow eccentric',false,null),
  ('we-anat-1-2','wt-anat-1','One-Arm_Dumbbell_Row',1,4,'10/side',75,7.0,'Squeeze 1s',false,null),
  ('we-anat-1-3','wt-anat-1','Dumbbell_Shoulder_Press',2,3,'10',60,6.5,'Pause top',false,null),
  ('we-anat-1-4','wt-anat-1','Dumbbell_Bicep_Curl',3,3,'12',45,6.0,'Slow tempo',false,null),
  ('we-anat-2-1','wt-anat-2','Goblet_Squat',0,4,'10',75,7.0,'Pause at bottom',false,null),
  ('we-anat-2-2','wt-anat-2','ex-003',1,4,'10',75,7.0,'Hinge focus',false,null),
  ('we-anat-2-3','wt-anat-2','Dumbbell_Lunges',2,3,'10/leg',60,6.5,'Slow descent',false,null),
  ('we-ctg-1-1','wt-ctg-1','Dumbbell_Bench_Press',0,5,'5',120,8.0,'Top set heavy',false,null),
  ('we-ctg-1-2','wt-ctg-1','Dumbbell_Shoulder_Press',1,4,'8',90,7.5,'Strict',false,null),
  ('we-ctg-1-3','wt-ctg-1','ex-018',2,3,'10',60,6.5,'Arnold press',false,null),
  ('we-ctg-2-1','wt-ctg-2','One-Arm_Dumbbell_Row',0,5,'8/side',90,8.0,'Heavy',false,null),
  ('we-ctg-2-2','wt-ctg-2','Dumbbell_Bicep_Curl',1,4,'10',60,7.0,'Strict',false,null),
  ('we-bl-1-1','wt-bl-1','ex-001',0,4,'10',90,7.0,'Heavy hip thrust',false,null),
  ('we-bl-1-2','wt-bl-1','ex-003',1,4,'10',75,7.0,'RDL — feel hamstrings',false,null),
  ('we-bl-1-3','wt-bl-1','ex-004',2,3,'15',45,6.5,'Banded',false,null),
  ('we-bl-1-4','wt-bl-1','ex-007',3,3,'12/side',45,6.0,'Lateral walks',false,null),
  ('we-bl-2-1','wt-bl-2','Goblet_Squat',0,4,'10',75,7.0,'Pause at bottom',false,null),
  ('we-bl-2-2','wt-bl-2','Dumbbell_Lunges',1,3,'10/leg',60,6.5,'Slow descent',false,null),
  ('we-bl-2-3','wt-bl-2','rehab-gl-001',2,3,'15',45,6.0,'Glute bridge',false,null),
  ('we-hyp-1-1','wt-hyp-1','Dumbbell_Bench_Press',0,4,'10-12',75,8.0,'RIR 1-2',false,null),
  ('we-hyp-1-2','wt-hyp-1','Dumbbell_Shoulder_Press',1,4,'10-12',75,7.5,'Strict',false,null),
  ('we-hyp-1-3','wt-hyp-1','ex-018',2,3,'12',60,7.0,'Arnold press',false,null),
  ('we-hyp-2-1','wt-hyp-2','One-Arm_Dumbbell_Row',0,4,'10-12/side',75,8.0,'Squeeze 1s',false,null),
  ('we-hyp-2-2','wt-hyp-2','Dumbbell_Bicep_Curl',1,4,'12',60,7.5,'Strict',false,null),
  ('we-nlm-1-1','wt-nlm-1','ex-032',0,5,'5',150,8.5,'Heavy back squat',false,null),
  ('we-nlm-1-2','wt-nlm-1','ex-003',1,4,'5',120,8.0,'Heavy RDL',false,null),
  ('we-nlm-1-3','wt-nlm-1','ex-001',2,3,'8',90,7.5,'Heavy hip thrust',false,null),
  ('we-nlm-2-1','wt-nlm-2','Dumbbell_Bench_Press',0,5,'5',120,8.5,'Heavy press',false,null),
  ('we-nlm-2-2','wt-nlm-2','ex-024',1,4,'6',120,8.0,'Barbell row',false,null),
  ('we-nlm-2-3','wt-nlm-2','Dumbbell_Shoulder_Press',2,3,'8',90,7.5,'Heavy',false,null),
  ('we-ash-1-1','wt-ash-1','ex-yog-005',0,5,'1 round',null,5.0,'Sun Salutation A',false,null),
  ('we-ash-1-2','wt-ash-1','ex-yog-008',1,1,'5 breaths',null,5.0,'Warrior I both sides',false,null),
  ('we-ash-1-3','wt-ash-1','ex-yog-009',2,1,'5 breaths',null,5.0,'Warrior II both sides',false,null),
  ('we-ash-2-1','wt-ash-2','ex-yog-010',0,1,'5 breaths',null,5.0,'Triangle pose',false,null),
  ('we-ash-2-2','wt-ash-2','ex-yog-012',1,1,'5 breaths',null,5.0,'Pigeon pose',false,null),
  ('we-ash-2-3','wt-ash-2','ex-yog-003',2,1,'5 breaths',null,4.0,'Downward dog',false,null),
  ('we-ash-2-4','wt-ash-2','ex-yog-004',3,1,'5 breaths',null,3.0,'Childs pose',false,null),
  ('we-rs-1-1','wt-rs-1','Hamstring_Stretch',0,3,'45s/side',30,4.0,'Contract 6s, release, deepen',false,null),
  ('we-rs-1-2','wt-rs-1','Quad_Stretch',1,3,'45s/side',30,4.0,'Hold gently',false,null),
  ('we-rs-1-3','wt-rs-1','str-050',2,3,'45s/side',30,4.0,'Hip flexor stretch',false,null),
  ('we-rs-2-1','wt-rs-2','str-008',0,3,'45s/side',30,4.0,'Thread the needle',false,null),
  ('we-se-1-1','wt-se-1','Hamstring_Stretch',0,2,'30s/side',15,3.0,null,false,null),
  ('we-se-1-2','wt-se-1','str-050',1,2,'30s/side',15,3.0,null,false,null),
  ('we-se-1-3','wt-se-1','rehab-hp-003',2,2,'30s/side',15,3.0,'Adductor stretch',false,null),
  ('we-se-2-1','wt-se-2','str-008',0,2,'30s/side',15,3.0,'Shoulder thread',false,null),
  ('we-se-2-2','wt-se-2','ex-yog-004',1,2,'45s',15,2.5,'Childs pose',false,null),
  ('we-som-1-1','wt-som-1','ex-som-001',0,5,'Slow reps',30,2.5,'Arch & flatten — half speed',false,null),
  ('we-som-2-1','wt-som-2','ex-som-001',0,5,'Slow reps',30,2.5,'Side variations',false,null),
  ('we-sha-1-1','wt-sha-1','Mountain_Climbers',0,3,'30s',45,7.0,'Quick feet',false,null),
  ('we-sha-1-2','wt-sha-1','ex-046',1,3,'10',60,7.5,'Burpee',false,null),
  ('we-sha-1-3','wt-sha-1','Plank',2,3,'45s',45,6.5,'Strong core for strikes',false,null),
  ('we-sha-1-4','wt-sha-1','Bodyweight_Squat',3,3,'20',45,6.0,'Horse stance practice',false,null),
  ('we-sha-2-1','wt-sha-2','ex-048',0,3,'30s',45,7.5,'High knees',false,null),
  ('we-sha-2-2','wt-sha-2','ex-047',1,3,'30s',45,8.0,'Jumping jacks',false,null),
  ('we-sha-2-3','wt-sha-2','ex-049',2,3,'30s',45,7.0,'Mountain climbers',false,null),
  ('we-fbb-1-1','wt-fbb-1','ex-032',0,4,'6',120,8.0,'Heavy back squat',false,null),
  ('we-fbb-1-2','wt-fbb-1','ex-003',1,4,'6',90,7.5,'RDL',false,null),
  ('we-fbb-1-3','wt-fbb-1','ex-001',2,3,'8',90,7.5,'Hip thrust',false,null),
  ('we-fbb-2-1','wt-fbb-2','Dumbbell_Bench_Press',0,4,'6',90,8.0,'Heavy',false,null),
  ('we-fbb-2-2','wt-fbb-2','One-Arm_Dumbbell_Row',1,4,'8/side',75,7.5,'Heavy',false,null),
  ('we-fbb-2-3','wt-fbb-2','Dumbbell_Shoulder_Press',2,3,'8',75,7.0,'Press',false,null),
  ('we-maf-1-1','wt-maf-1','ex-048',0,1,'30 min',null,4.0,'Steady jog/walk at MAF HR',false,null),
  ('we-maf-2-1','wt-maf-2','ex-048',0,1,'45 min',null,4.0,'Steady MAF effort — keep HR under 180 minus age',false,null),
  ('we-thr-1-1','wt-thr-1','ex-048',0,1,'40 min',null,5.0,'Conversational zone 2',false,null),
  ('we-thr-2-1','wt-thr-2','ex-046',0,4,'4 min',180,8.0,'Burpees 4 min hard / 3 min walk',false,null),
  ('we-bbg-1-1','wt-bbg-1','ex-039',0,4,'15',null,7.5,'Jump squats — circuit',true,'A'),
  ('we-bbg-1-2','wt-bbg-1','Dumbbell_Lunges',1,4,'10/leg',null,7.5,'Lunges — circuit',true,'A'),
  ('we-bbg-1-3','wt-bbg-1','rehab-gl-001',2,4,'15',null,7.0,'Glute bridge — circuit',true,'A'),
  ('we-bbg-1-4','wt-bbg-1','ex-046',3,4,'8',null,8.0,'Burpees — circuit',true,'A'),
  ('we-bbg-2-1','wt-bbg-2','ex-014',0,4,'10',null,7.5,'Push-ups — circuit',true,'A'),
  ('we-bbg-2-2','wt-bbg-2','Russian_Twist',1,4,'20',null,7.0,'Twists — circuit',true,'A'),
  ('we-bbg-2-3','wt-bbg-2','Plank',2,4,'45s',null,7.0,'Plank — circuit',true,'A'),
  ('we-bbg-2-4','wt-bbg-2','Mountain_Climbers',3,4,'30s',null,7.5,'Climbers — circuit',true,'A')
ON CONFLICT (id) DO NOTHING;
